name: Development Builds

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Releasing for macOS
      run: | 
        dotnet publish -c Release -r osx-x64 --self-contained true
        zip -r osx-x64-self-contained.zip ./bin/Release/net5.0/osx-x64
    - name: Releasing for Linux
      run: |
        dotnet publish -c Release -r linux-x64 --self-contained true
        zip -r linux-x64-self-contained.zip ./bin/Release/net5.0/linux-x64
    - name: Releasing for Windows
      run: | 
        dotnet publish -c Release -r win-x64 --self-contained true
        zip -r win-x64-self-contained.zip ./bin/Release/net5.0/win-x64
        ls -lacs
    - uses: actions/checkout@v2
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: |
          osx-x64-self-contained.zip
          linux-x64-self-contained.zip
          win-x64-self-contained.zip
